export type CategoryKey = "coffee" | "tea" | "breakfast" | "pastry" | "cold" | "brunch";

export interface MenuItem {
  id: string;
  category: CategoryKey;
  name: { fa: string; en: string };
  desc: { fa: string; en: string };
  price: number; // Toman
  popular?: boolean;
  vegetarian?: boolean;
  isNew?: boolean;
  /**
   * images.unsplash.com photo ID, present only for the handful of items
   * where a real, accurately-matching, freely-licensed photo was found.
   */
  unsplashId?: string;
  /** Path under /public for a user-supplied photo of this exact dish, e.g. "/menu-photos/mirza.jpg". */
  localPhoto?: string;
}

export const categoryOrder: CategoryKey[] = [
  "coffee",
  "tea",
  "cold",
  "breakfast",
  "brunch",
  "pastry",
];

export const menuItems: MenuItem[] = [
  {
    id: "espresso",
    category: "coffee",
    name: { fa: "اسپرسو", en: "Espresso" },
    desc: { fa: "دولوچ اتیوپی، تک‌خاستگاه", en: "Single-origin Ethiopian Doluch" },
    price: 65000,
    popular: true,
    vegetarian: true,
    localPhoto: "/menu-photos/espresso.webp",
  },
  {
    id: "cortado",
    category: "coffee",
    name: { fa: "کورتادو", en: "Cortado" },
    desc: { fa: "اسپرسو با شیر بخارداده به نسبت برابر", en: "Equal parts espresso and steamed milk" },
    price: 95000,
    popular: true,
    vegetarian: true,
    localPhoto: "/menu-photos/cortado.webp",
  },
  {
    id: "flat-white",
    category: "coffee",
    name: { fa: "فلت وایت", en: "Flat White" },
    desc: { fa: "دو شات ریسترتو با میکروفوم مخملی", en: "Double ristretto, velvety microfoam" },
    price: 105000,
    vegetarian: true,
    localPhoto: "/menu-photos/flat-white.webp",
  },
  {
    id: "turkish",
    category: "coffee",
    name: { fa: "قهوه‌ی دیوان", en: "Divan Coffee" },
    desc: { fa: "دم‌آوری سنتی روی شن داغ، امضای دیوان", en: "Traditional hot-sand brew, Divan signature" },
    price: 90000,
    isNew: true,
    vegetarian: true,
    unsplashId: "1576685880864-50b3b35f1c55",
  },
  {
    id: "pour-over",
    category: "coffee",
    name: { fa: "دم‌آوری V60", en: "V60 Pour-Over" },
    desc: { fa: "انتخاب هفتگی رست‌مستر", en: "Roastmaster's weekly single-origin" },
    price: 120000,
    vegetarian: true,
    localPhoto: "/menu-photos/pour-over.webp",
  },
  {
    id: "cold-brew",
    category: "cold",
    name: { fa: "کلد برو", en: "Cold Brew" },
    desc: { fa: "دم‌آوری ۱۸ ساعته، یخ کند-آب‌شونده", en: "18-hour steep, slow-melt ice" },
    price: 98000,
    popular: true,
    vegetarian: true,
    localPhoto: "/menu-photos/cold-brew.webp",
  },
  {
    id: "iced-shekar",
    category: "cold",
    name: { fa: "شکرقهوه یخ", en: "Iced Shekar Coffee" },
    desc: { fa: "اسپرسو، شیر بادام، شکر سوخته", en: "Espresso, almond milk, burnt sugar" },
    price: 108000,
    isNew: true,
    vegetarian: true,
    localPhoto: "/menu-photos/iced-shekar.webp",
  },
  {
    id: "sekanjabin-fizz",
    category: "cold",
    name: { fa: "سکنجبین فیز", en: "Sekanjabin Fizz" },
    desc: { fa: "سکنجبین خانگی، سودا، برگ نعنا", en: "House sekanjabin syrup, soda, mint" },
    price: 88000,
    vegetarian: true,
    localPhoto: "/menu-photos/sekanjabin-fizz.webp",
  },
  {
    id: "saffron-latte",
    category: "tea",
    name: { fa: "دمنوش زعفران و هل", en: "Saffron Cardamom Infusion" },
    desc: { fa: "زعفران قاینات، هل، عسل کوهستان", en: "Qaenat saffron, cardamom, mountain honey" },
    price: 92000,
    popular: true,
    vegetarian: true,
    localPhoto: "/menu-photos/saffron-latte.webp",
  },
  {
    id: "chai-bahar",
    category: "tea",
    name: { fa: "چای بهارنارنج", en: "Bitter Orange Blossom Tea" },
    desc: { fa: "چای لاهیجان با گلاب بهارنارنج", en: "Lahijan black tea with orange blossom water" },
    price: 70000,
    vegetarian: true,
    localPhoto: "/menu-photos/chai-bahar.webp",
  },
  {
    id: "sohan-latte",
    category: "tea",
    name: { fa: "دمنوش زنجبیل و دارچین", en: "Ginger Cinnamon Infusion" },
    desc: { fa: "زنجبیل تازه، دارچین سیلان، لیموعمانی", en: "Fresh ginger, Ceylon cinnamon, dried lime" },
    price: 75000,
    vegetarian: true,
    localPhoto: "/menu-photos/sohan-latte.webp",
  },
  {
    id: "eggs-kuku",
    category: "breakfast",
    name: { fa: "کوکو سبزی و تخم‌مرغ عسلی", en: "Herb Kuku & Honeyed Eggs" },
    desc: { fa: "با نان بربری تازه و کره‌ی محلی", en: "Served with warm barbari and local butter" },
    price: 175000,
    popular: true,
    vegetarian: true,
    localPhoto: "/menu-photos/eggs-kuku.webp",
  },
  {
    id: "panir-sabzi",
    category: "breakfast",
    name: { fa: "سفره‌ی پنیر و سبزی", en: "Cheese & Herb Spread" },
    desc: { fa: "پنیر لیقوان، گردو، سبزی خوردن، مربای به", en: "Lighvan cheese, walnuts, herbs, quince jam" },
    price: 165000,
    vegetarian: true,
    localPhoto: "/menu-photos/panir-sabzi.webp",
  },
  {
    id: "shakshuka",
    category: "breakfast",
    name: { fa: "شکشوکای دیوان", en: "Divan Shakshuka" },
    desc: { fa: "تخم‌مرغ در سس گوجه و فلفل دودی", en: "Eggs poached in smoky pepper-tomato sauce" },
    price: 195000,
    isNew: true,
    vegetarian: true,
    localPhoto: "/menu-photos/shakshuka.webp",
  },
  {
    id: "kalam-polo",
    category: "brunch",
    name: { fa: "کلم‌پلو با کوفته‌ی خانگی", en: "Cabbage Rice with House Meatballs" },
    desc: { fa: "دستور خانگی مادربزرگ سرآشپز", en: "The chef's grandmother's recipe" },
    price: 320000,
    popular: true,
    localPhoto: "/menu-photos/kalam-polo.webp",
  },
  {
    id: "zeytoon-koofte",
    category: "brunch",
    name: { fa: "کوفته زیتون گیلانی", en: "Gilani Olive Kufteh" },
    desc: { fa: "گوشت گوسفندی، زیتون، آلو، آب‌نارنج", en: "Lamb, olives, sour plum, bitter orange" },
    price: 340000,
    localPhoto: "/menu-photos/zeytoon-koofte.webp",
  },
  {
    id: "mirza",
    category: "brunch",
    name: { fa: "میرزاقاسمی با نان تست", en: "Mirza Ghasemi with Toast" },
    desc: { fa: "بادمجان دودی، گوجه، تخم‌مرغ", en: "Smoked eggplant, tomato, egg" },
    price: 245000,
    vegetarian: true,
    localPhoto: "/menu-photos/mirza.webp",
  },
  {
    id: "baklava",
    category: "pastry",
    name: { fa: "باقلوای دیوان", en: "Divan Baklava" },
    desc: { fa: "پسته اصفهان، عسل، گلاب", en: "Isfahan pistachio, honey, rosewater" },
    price: 78000,
    popular: true,
    vegetarian: true,
    unsplashId: "1702745284711-fc5668288afa",
  },
  {
    id: "saffron-croissant",
    category: "pastry",
    name: { fa: "کروسان زعفرانی", en: "Saffron Croissant" },
    desc: { fa: "خمیر لایه‌ای با فیلینگ زعفران و خامه", en: "Laminated dough, saffron cream filling" },
    price: 95000,
    isNew: true,
    vegetarian: true,
    unsplashId: "1668446377138-c763c16e99f0",
  },
  {
    id: "walnut-cake",
    category: "pastry",
    name: { fa: "کیک گردو و خرما", en: "Walnut Date Cake" },
    desc: { fa: "بدون شکر تصفیه‌شده، با کارامل خرما", en: "No refined sugar, date caramel" },
    price: 85000,
    vegetarian: true,
    localPhoto: "/menu-photos/walnut-cake.webp",
  },

  {
    id: "doppio",
    category: "coffee",
    name: { fa: "دابل اسپرسو", en: "Doppio" },
    desc: { fa: "دو شات اسپرسو غلیظ", en: "Double shot of concentrated espresso" },
    price: 78000,
    vegetarian: true,
    localPhoto: "/menu-photos/doppio.webp",
  },
  {
    id: "americano",
    category: "coffee",
    name: { fa: "آمریکانو", en: "Americano" },
    desc: { fa: "اسپرسو، آب داغ", en: "Espresso, hot water" },
    price: 72000,
    vegetarian: true,
    localPhoto: "/menu-photos/americano.webp",
  },
  {
    id: "cappuccino",
    category: "coffee",
    name: { fa: "کاپوچینو", en: "Cappuccino" },
    desc: { fa: "اسپرسو، شیر بخارداده، کف شیر", en: "Espresso, steamed milk, milk foam" },
    price: 98000,
    popular: true,
    isNew: true,
    vegetarian: true,
    localPhoto: "/menu-photos/cappuccino.webp",
  },
  {
    id: "latte",
    category: "coffee",
    name: { fa: "کافه لاته", en: "Caffè Latte" },
    desc: { fa: "اسپرسو، شیر بخارداده، کف نازک", en: "Espresso, steamed milk, light foam" },
    price: 100000,
    vegetarian: true,
    localPhoto: "/menu-photos/latte.webp",
  },
  {
    id: "mocha",
    category: "coffee",
    name: { fa: "موکا", en: "Mocha" },
    desc: { fa: "اسپرسو، شیر بخارداده، شکلات تلخ، خامه", en: "Espresso, steamed milk, dark chocolate, cream" },
    price: 108000,
    vegetarian: true,
    localPhoto: "/menu-photos/mocha.webp",
  },
  {
    id: "caramel-macchiato",
    category: "coffee",
    name: { fa: "کارامل ماکیاتو", en: "Caramel Macchiato" },
    desc: { fa: "اسپرسو، شیر بخارداده، سس کارامل", en: "Espresso, steamed milk, caramel sauce" },
    price: 112000,
    vegetarian: true,
    localPhoto: "/menu-photos/caramel-macchiato.webp",
  },
  {
    id: "iced-americano",
    category: "cold",
    name: { fa: "آیس آمریکانو", en: "Iced Americano" },
    desc: { fa: "اسپرسو، آب سرد، یخ", en: "Espresso, cold water, ice" },
    price: 78000,
    vegetarian: true,
    localPhoto: "/menu-photos/iced-americano.webp",
  },
  {
    id: "iced-latte",
    category: "cold",
    name: { fa: "آیس لاته", en: "Iced Latte" },
    desc: { fa: "اسپرسو، شیر سرد، یخ", en: "Espresso, cold milk, ice" },
    price: 102000,
    vegetarian: true,
    localPhoto: "/menu-photos/iced-latte.webp",
  },
  {
    id: "iced-mocha",
    category: "cold",
    name: { fa: "آیس موکا", en: "Iced Mocha" },
    desc: { fa: "اسپرسو، شیر سرد، شکلات، یخ", en: "Espresso, cold milk, chocolate, ice" },
    price: 112000,
    vegetarian: true,
    localPhoto: "/menu-photos/iced-mocha.webp",
  },
  {
    id: "frappuccino",
    category: "cold",
    name: { fa: "فراپوچینو", en: "Frappuccino" },
    desc: { fa: "اسپرسو یخ‌زده، شیر، خامه", en: "Blended iced espresso, milk, cream" },
    price: 118000,
    popular: true,
    isNew: true,
    vegetarian: true,
    localPhoto: "/menu-photos/frappuccino.webp",
  },
  {
    id: "caramel-frappuccino",
    category: "cold",
    name: { fa: "فراپوچینو کارامل", en: "Caramel Frappuccino" },
    desc: { fa: "اسپرسو یخ‌زده، شیر، سس کارامل، خامه", en: "Blended iced espresso, milk, caramel, cream" },
    price: 122000,
    vegetarian: true,
    localPhoto: "/menu-photos/caramel-frappuccino.webp",
  },
  {
    id: "lemonade",
    category: "cold",
    name: { fa: "لیموناد خانگی", en: "House Lemonade" },
    desc: { fa: "لیمو تازه، نعنا، شربت", en: "Fresh lemon, mint, syrup" },
    price: 82000,
    vegetarian: true,
    localPhoto: "/menu-photos/lemonade.webp",
  },
  {
    id: "iced-tea-fresh",
    category: "cold",
    name: { fa: "آیس تی", en: "Iced Tea" },
    desc: { fa: "چای سیاه، لیمو، یخ", en: "Black tea, lemon, ice" },
    price: 76000,
    vegetarian: true,
    localPhoto: "/menu-photos/iced-tea.webp",
  },
  {
    id: "berry-smoothie",
    category: "cold",
    name: { fa: "اسموتی توت‌های وحشی", en: "Mixed Berry Smoothie" },
    desc: { fa: "توت‌فرنگی، ماست، عسل", en: "Strawberry, yogurt, honey" },
    price: 105000,
    vegetarian: true,
    localPhoto: "/menu-photos/berry-smoothie.webp",
  },
  {
    id: "black-tea",
    category: "tea",
    name: { fa: "چای سیاه", en: "Black Tea" },
    desc: { fa: "برگ چای سیاه درجه یک", en: "Premium black tea leaves" },
    price: 62000,
    vegetarian: true,
    localPhoto: "/menu-photos/black-tea.webp",
  },
  {
    id: "green-tea",
    category: "tea",
    name: { fa: "چای سبز", en: "Green Tea" },
    desc: { fa: "برگ چای سبز ژاپنی", en: "Japanese green tea leaves" },
    price: 65000,
    vegetarian: true,
    localPhoto: "/menu-photos/green-tea.webp",
  },
  {
    id: "chamomile-tea",
    category: "tea",
    name: { fa: "دمنوش بابونه", en: "Chamomile Infusion" },
    desc: { fa: "گل بابونه خشک", en: "Dried chamomile flowers" },
    price: 68000,
    vegetarian: true,
    localPhoto: "/menu-photos/chamomile-tea.webp",
  },
  {
    id: "mint-tea",
    category: "tea",
    name: { fa: "دمنوش نعنا", en: "Mint Infusion" },
    desc: { fa: "برگ نعنای تازه، عسل", en: "Fresh mint leaves, honey" },
    price: 68000,
    vegetarian: true,
    localPhoto: "/menu-photos/mint-tea.webp",
  },
  {
    id: "hibiscus-tea",
    category: "tea",
    name: { fa: "دمنوش چای ترش", en: "Hibiscus Tea" },
    desc: { fa: "گلبرگ ترش، دارچین", en: "Dried hibiscus petals, cinnamon" },
    price: 72000,
    vegetarian: true,
    localPhoto: "/menu-photos/hibiscus-tea.webp",
  },
  {
    id: "ginger-lemon-tea",
    category: "tea",
    name: { fa: "دمنوش زنجبیل و لیمو", en: "Ginger Lemon Tea" },
    desc: { fa: "زنجبیل تازه، لیمو، عسل", en: "Fresh ginger, lemon, honey" },
    price: 75000,
    vegetarian: true,
    localPhoto: "/menu-photos/ginger-lemon-tea.webp",
  },
  {
    id: "masala-chai",
    category: "tea",
    name: { fa: "چای ماسالای هندی", en: "Masala Chai" },
    desc: { fa: "چای سیاه، دارچین، هل، شیر", en: "Black tea, cinnamon, cardamom, milk" },
    price: 85000,
    vegetarian: true,
    localPhoto: "/menu-photos/masala-chai.webp",
  },
  {
    id: "chai-latte",
    category: "tea",
    name: { fa: "چای لاته", en: "Chai Latte" },
    desc: { fa: "دمنوش چای ادویه‌دار، شیر بخارداده", en: "Spiced tea concentrate, steamed milk" },
    price: 92000,
    vegetarian: true,
    localPhoto: "/menu-photos/chai-latte.webp",
  },
  {
    id: "tiramisu",
    category: "pastry",
    name: { fa: "تیرامیسو", en: "Tiramisu" },
    desc: { fa: "ماسکارپونه، قهوه، بیسکویت لیدی‌فینگر، کاکائو", en: "Mascarpone, espresso, ladyfingers, cocoa" },
    price: 115000,
    popular: true,
    isNew: true,
    vegetarian: true,
    localPhoto: "/menu-photos/tiramisu.webp",
  },
  {
    id: "cheesecake",
    category: "pastry",
    name: { fa: "چیزکیک نیویورکی", en: "New York Cheesecake" },
    desc: { fa: "پنیر خامه‌ای، بیسکویت، سس توت", en: "Cream cheese, biscuit base, berry sauce" },
    price: 110000,
    vegetarian: true,
    localPhoto: "/menu-photos/cheesecake.webp",
  },
  {
    id: "brownie",
    category: "pastry",
    name: { fa: "براونی شکلاتی", en: "Chocolate Brownie" },
    desc: { fa: "شکلات تلخ، گردو، کره", en: "Dark chocolate, walnuts, butter" },
    price: 88000,
    vegetarian: true,
    localPhoto: "/menu-photos/brownie.webp",
  },
  {
    id: "carrot-cake",
    category: "pastry",
    name: { fa: "کیک هویج", en: "Carrot Cake" },
    desc: { fa: "هویج، گردو، دارچین، خامه پنیر", en: "Carrot, walnuts, cinnamon, cream-cheese frosting" },
    price: 95000,
    vegetarian: true,
    localPhoto: "/menu-photos/carrot-cake.webp",
  },
  {
    id: "lemon-tart",
    category: "pastry",
    name: { fa: "تارت لیمو با مرنگ", en: "Lemon Meringue Tart" },
    desc: { fa: "کرم لیمو، مرنگ، خمیر شکری", en: "Lemon curd, torched meringue, shortcrust" },
    price: 98000,
    vegetarian: true,
    localPhoto: "/menu-photos/lemon-tart.webp",
  },
  {
    id: "panna-cotta",
    category: "pastry",
    name: { fa: "پاناکوتا با سس توت", en: "Panna Cotta" },
    desc: { fa: "خامه، وانیل، سس توت قرمز", en: "Cream, vanilla, red berry sauce" },
    price: 92000,
    vegetarian: true,
    localPhoto: "/menu-photos/panna-cotta.webp",
  },
  {
    id: "creme-brulee-2",
    category: "pastry",
    name: { fa: "کرم بروله", en: "Crème Brûlée" },
    desc: { fa: "خامه، وانیل، کارامل سوخته", en: "Custard cream, vanilla, torched caramel" },
    price: 105000,
    vegetarian: true,
    localPhoto: "/menu-photos/creme-brulee.webp",
  },
  {
    id: "macarons",
    category: "pastry",
    name: { fa: "ماکارون فرانسوی", en: "French Macarons" },
    desc: { fa: "بادام، سفیده تخم‌مرغ، کرم داخلی", en: "Almond flour, egg white, buttercream filling" },
    price: 85000,
    isNew: true,
    vegetarian: true,
    localPhoto: "/menu-photos/macarons.webp",
  },
  {
    id: "chocolate-lava-cake",
    category: "pastry",
    name: { fa: "کیک لاوا شکلاتی", en: "Chocolate Lava Cake" },
    desc: { fa: "شکلات تلخ، کره، هسته‌ی مذاب", en: "Dark chocolate, butter, molten center" },
    price: 118000,
    popular: true,
    isNew: true,
    vegetarian: true,
    localPhoto: "/menu-photos/chocolate-lava-cake.webp",
  },
  {
    id: "waffle",
    category: "pastry",
    name: { fa: "وافل با میوه و بستنی", en: "Waffle with Fruit & Ice Cream" },
    desc: { fa: "خمیر وافل، توت‌های تازه، بستنی وانیل", en: "Waffle batter, fresh berries, vanilla ice cream" },
    price: 125000,
    vegetarian: true,
    localPhoto: "/menu-photos/waffle.webp",
  },
  {
    id: "pancakes",
    category: "pastry",
    name: { fa: "پنکیک با توت و شربت افرا", en: "Pancakes with Berries & Maple Syrup" },
    desc: { fa: "پنکیک لایه‌ای، توت‌فرنگی، شربت افرا", en: "Stacked pancakes, strawberries, maple syrup" },
    price: 105000,
    vegetarian: true,
    localPhoto: "/menu-photos/pancakes.webp",
  },
  {
    id: "croissant-plain",
    category: "pastry",
    name: { fa: "کروسان کره‌ای", en: "Butter Croissant" },
    desc: { fa: "خمیر لایه‌ای کره‌ای فرانسوی", en: "French laminated butter dough" },
    price: 68000,
    vegetarian: true,
    localPhoto: "/menu-photos/croissant-plain.webp",
  },
  {
    id: "chocolate-cake",
    category: "pastry",
    name: { fa: "کیک شکلاتی سه‌لایه", en: "Triple Chocolate Cake" },
    desc: { fa: "شکلات تلخ، گاناش، خامه", en: "Dark chocolate, ganache, cream" },
    price: 108000,
    vegetarian: true,
    localPhoto: "/menu-photos/chocolate-cake.webp",
  },
  {
    id: "cinnamon-roll",
    category: "pastry",
    name: { fa: "رول دارچین با گلیز", en: "Cinnamon Roll" },
    desc: { fa: "خمیر شیرین، دارچین، گلیز کره‌ای", en: "Sweet dough, cinnamon, butter glaze" },
    price: 78000,
    vegetarian: true,
    localPhoto: "/menu-photos/cinnamon-roll.webp",
  },
  {
    id: "fruit-tart",
    category: "pastry",
    name: { fa: "تارت میوه‌های فصل", en: "Seasonal Fruit Tart" },
    desc: { fa: "خامه وانیل، میوه‌های تازه، خمیر شکری", en: "Vanilla cream, fresh fruit, shortcrust" },
    price: 98000,
    vegetarian: true,
    localPhoto: "/menu-photos/fruit-tart.webp",
  },
  {
    id: "loobia-polo",
    category: "brunch",
    name: { fa: "لوبیا پلو با گوشت", en: "Green Bean Rice with Beef" },
    desc: { fa: "لوبیا سبز، گوجه‌فرنگی، گوشت چرخ‌کرده، زعفران", en: "Green beans, tomato, ground beef, saffron" },
    price: 310000,
    localPhoto: "/menu-photos/loobia-polo.webp",
  },
  {
    id: "khoresh-havij",
    category: "brunch",
    name: { fa: "چلو خورشت هویج", en: "Carrot Stew with Rice" },
    desc: { fa: "خورش هویج و گوشت با زعفران و لیمو عمانی", en: "Carrot and beef stew, saffron, dried lime" },
    price: 300000,
    localPhoto: "/menu-photos/khoresh-havij.webp",
  },
  {
    id: "khoresh-karafs",
    category: "brunch",
    name: { fa: "چلو خورشت کرفس", en: "Celery Stew with Rice" },
    desc: { fa: "کرفس، گوشت، رب گوجه‌فرنگی و زردچوبه", en: "Celery, beef, tomato paste, turmeric" },
    price: 300000,
    localPhoto: "/menu-photos/khoresh-karafs.webp",
  },
  {
    id: "ferni",
    category: "brunch",
    name: { fa: "فرنی", en: "Ferni (Rice Pudding)" },
    desc: { fa: "شیر، برنج، گلاب، دارچین و پسته خلالی", en: "Milk, rice, rosewater, cinnamon, slivered pistachio" },
    price: 95000,
    vegetarian: true,
    localPhoto: "/menu-photos/ferni.webp",
  },
  {
    id: "khoresh-lapeh",
    category: "brunch",
    name: { fa: "چلو خورشت لپه", en: "Split Pea Stew with Rice" },
    desc: { fa: "لپه، گوشت، پیاز و دارچین", en: "Split peas, beef, onion, cinnamon" },
    price: 295000,
    localPhoto: "/menu-photos/khoresh-lapeh.webp",
  },
  {
    id: "khoresh-aloo-esfenaj",
    category: "brunch",
    name: { fa: "چلو خورشت آلو اسفناج", en: "Prune & Spinach Stew with Rice" },
    desc: { fa: "اسفناج، آلو، گوشت و لیموترش", en: "Spinach, prunes, beef, sour lime" },
    price: 305000,
    localPhoto: "/menu-photos/khoresh-aloo-esfenaj.webp",
  },
  {
    id: "omlet-sabzijat",
    category: "brunch",
    name: { fa: "املت سبزیجات", en: "Vegetable Omelet" },
    desc: { fa: "تخم‌مرغ، سبزی تازه و کمی فلفل سیاه", en: "Eggs, fresh herbs, black pepper" },
    price: 175000,
    vegetarian: true,
    localPhoto: "/menu-photos/omlet-sabzijat.webp",
  },
  {
    id: "khoresh-khalal-badam",
    category: "brunch",
    name: { fa: "چلو خورشت خلال بادام", en: "Almond Sliver Stew with Rice" },
    desc: { fa: "گوشت، خلال بادام و زعفران", en: "Beef, slivered almonds, saffron" },
    price: 330000,
    localPhoto: "/menu-photos/khoresh-khalal-badam.webp",
  },
  {
    id: "kashk-bademjan",
    category: "brunch",
    name: { fa: "کشک بادمجان", en: "Kashk-e Bademjan" },
    desc: { fa: "بادمجان سرخ‌شده، کشک، پیازداغ و نعناع داغ", en: "Fried eggplant, kashk, fried onion and mint" },
    price: 185000,
    vegetarian: true,
    localPhoto: "/menu-photos/kashk-bademjan.webp",
  },
  {
    id: "komaj",
    category: "brunch",
    name: { fa: "کماج", en: "Komaj Bread" },
    desc: { fa: "نان سنتی جنوبی با خرما، هل و دارچین", en: "Traditional southern bread with date, cardamom, cinnamon" },
    price: 65000,
    vegetarian: true,
    localPhoto: "/menu-photos/komaj.webp",
  },
  {
    id: "ash-shole-ghalamkar",
    category: "brunch",
    name: { fa: "آش شله‌قلمکار", en: "Ash-e Sholeh Qalamkar" },
    desc: { fa: "لپه، برنج، سبزی معطر و کوفته ریز", en: "Split peas, rice, fresh herbs, tiny meatballs" },
    price: 165000,
    localPhoto: "/menu-photos/ash-shole-ghalamkar.webp",
  },
  {
    id: "ash-reshteh",
    category: "brunch",
    name: { fa: "آش رشته", en: "Ash Reshteh" },
    desc: { fa: "رشته، حبوبات، سبزی آش، کشک و نعناع داغ", en: "Noodles, legumes, herbs, kashk, fried mint" },
    price: 155000,
    vegetarian: true,
    localPhoto: "/menu-photos/ash-reshteh.webp",
  },
  {
    id: "ash-jo",
    category: "brunch",
    name: { fa: "آش جو", en: "Barley Soup" },
    desc: { fa: "جو پرک، مرغ، هویج و نعناع داغ", en: "Pearl barley, chicken, carrot, fried mint" },
    price: 145000,
    localPhoto: "/menu-photos/ash-jo.webp",
  },
  {
    id: "khoresh-gheimeh",
    category: "brunch",
    name: { fa: "چلو خورشت قیمه", en: "Gheimeh Stew with Rice" },
    desc: { fa: "لپه، گوشت، سیب‌زمینی سرخ‌کرده و لیمو عمانی", en: "Split peas, beef, crispy potato, dried lime" },
    price: 300000,
    popular: true,
    localPhoto: "/menu-photos/khoresh-gheimeh.webp",
  },
  {
    id: "omlet-gharch",
    category: "brunch",
    name: { fa: "املت قارچ", en: "Mushroom Omelet" },
    desc: { fa: "تخم‌مرغ، قارچ تازه و پیاز قرمز", en: "Eggs, fresh mushroom, red onion" },
    price: 180000,
    vegetarian: true,
    localPhoto: "/menu-photos/omlet-gharch.webp",
  },
  {
    id: "khoresh-fesenjan",
    category: "brunch",
    name: { fa: "چلو خورشت فسنجان", en: "Fesenjan Stew with Rice" },
    desc: { fa: "مرغ، رب انار، گردو و زعفران", en: "Chicken, pomegranate molasses, walnuts, saffron" },
    price: 340000,
    popular: true,
    localPhoto: "/menu-photos/khoresh-fesenjan.webp",
  },
  {
    id: "kalam-polo-shirazi",
    category: "brunch",
    name: { fa: "کلم پلو شیرازی", en: "Shirazi Cabbage Rice" },
    desc: { fa: "برنج، کلم سفید، سبزی معطر و آلو", en: "Rice, white cabbage, fresh herbs, dried plum" },
    price: 285000,
    vegetarian: true,
    localPhoto: "/menu-photos/kalam-polo-shirazi.webp",
  },
  {
    id: "khoresh-aloo",
    category: "brunch",
    name: { fa: "چلو خورشت آلو", en: "Prune Stew with Rice" },
    desc: { fa: "گوشت، آلو، خلال بادام و زعفران", en: "Beef, prunes, slivered almonds, saffron" },
    price: 315000,
    localPhoto: "/menu-photos/khoresh-aloo.webp",
  },
  {
    id: "morassa-polo",
    category: "brunch",
    name: { fa: "مرصع پلو", en: "Morasa Polo (Jeweled Rice)" },
    desc: { fa: "برنج زعفرانی، خلال پرتقال، زرشک، بادام و پسته", en: "Saffron rice, candied orange peel, barberry, almonds, pistachio" },
    price: 340000,
    popular: true,
    localPhoto: "/menu-photos/morassa-polo.webp",
  },
  {
    id: "adas-polo",
    category: "brunch",
    name: { fa: "عدس پلو با گوشت", en: "Lentil Rice with Beef" },
    desc: { fa: "عدس، کشمش، برنج و داغ زعفران", en: "Lentils, raisins, rice, saffron" },
    price: 300000,
    localPhoto: "/menu-photos/adas-polo.webp",
  },
  {
    id: "sholeh-zard",
    category: "brunch",
    name: { fa: "شله زرد", en: "Sholeh Zard" },
    desc: { fa: "برنج، زعفران، گلاب، خلال بادام و پسته", en: "Rice, saffron, rosewater, slivered almond and pistachio" },
    price: 90000,
    vegetarian: true,
    localPhoto: "/menu-photos/sholeh-zard.webp",
  },
  {
    id: "halim",
    category: "brunch",
    name: { fa: "حلیم", en: "Halim" },
    desc: { fa: "گندم، گوشت، دارچین و کمی کشک", en: "Wheat, beef, cinnamon, a touch of kashk" },
    price: 150000,
    localPhoto: "/menu-photos/halim.webp",
  },
  {
    id: "khoresh-ghormeh-sabzi",
    category: "brunch",
    name: { fa: "چلو خورشت قورمه سبزی", en: "Ghormeh Sabzi Stew with Rice" },
    desc: { fa: "سبزی قورمه، لوبیا قرمز، گوشت و لیمو عمانی", en: "Fresh herbs, red beans, beef, dried lime" },
    price: 320000,
    popular: true,
    localPhoto: "/menu-photos/khoresh-ghormeh-sabzi.webp",
  },
  {
    id: "joojeh-kabab",
    category: "brunch",
    name: { fa: "چلو جوجه کباب", en: "Chicken Kabab with Rice" },
    desc: { fa: "سینه مرغ زعفرانی، آبلیمو و کره", en: "Saffron chicken breast, lime, butter" },
    price: 360000,
    popular: true,
    localPhoto: "/menu-photos/joojeh-kabab.webp",
  },
  {
    id: "kabab-koobideh",
    category: "brunch",
    name: { fa: "چلو کباب کوبیده", en: "Koobideh Kabab with Rice" },
    desc: { fa: "گوشت گوسفندی چرخ‌کرده، پیاز و کره", en: "Ground lamb, onion, butter" },
    price: 370000,
    popular: true,
    localPhoto: "/menu-photos/kabab-koobideh.webp",
  },
  {
    id: "zereshk-polo-morgh",
    category: "brunch",
    name: { fa: "زرشک پلو با مرغ", en: "Barberry Rice with Chicken" },
    desc: { fa: "مرغ، برنج زعفرانی و زرشک", en: "Chicken, saffron rice, barberries" },
    price: 330000,
    popular: true,
    localPhoto: "/menu-photos/zereshk-polo-morgh.webp",
  },
  {
    id: "khoresh-bamieh",
    category: "brunch",
    name: { fa: "چلو خورشت بامیه", en: "Okra Stew with Rice" },
    desc: { fa: "بامیه، مرغ، گوجه‌فرنگی و زردچوبه", en: "Okra, chicken, tomato, turmeric" },
    price: 300000,
    localPhoto: "/menu-photos/khoresh-bamieh.webp",
  },
  {
    id: "meygoo-polo",
    category: "brunch",
    name: { fa: "میگو پلو", en: "Shrimp Rice" },
    desc: { fa: "میگو، شوید، سیر و زعفران", en: "Shrimp, dill, garlic, saffron" },
    price: 350000,
    localPhoto: "/menu-photos/meygoo-polo.webp",
  },
  {
    id: "baghali-polo-machehe",
    category: "brunch",
    name: { fa: "باقالی پلو با ماهیچه", en: "Lamb Shank with Lima Bean Rice" },
    desc: { fa: "ماهیچه گوسفندی، باقالی، شوید و زعفران", en: "Lamb shank, lima beans, dill, saffron" },
    price: 420000,
    popular: true,
    localPhoto: "/menu-photos/baghali-polo-machehe.webp",
  },
  {
    id: "omlet-gojeh",
    category: "brunch",
    name: { fa: "املت گوجه‌فرنگی", en: "Tomato Omelet" },
    desc: { fa: "تخم‌مرغ، گوجه‌فرنگی تازه و پیاز", en: "Eggs, fresh tomato, onion" },
    price: 175000,
    vegetarian: true,
    localPhoto: "/menu-photos/omlet-gojeh.webp",
  },
];

export const popularItems = menuItems.filter((item) => item.popular);

/** Number of menu items per category, derived from menuItems so it can never go stale. */
export const categoryCounts: Record<CategoryKey, number> = categoryOrder.reduce(
  (acc, key) => {
    acc[key] = menuItems.filter((item) => item.category === key).length;
    return acc;
  },
  {} as Record<CategoryKey, number>
);

export interface AmbianceFeature {
  key: "interior" | "courtyard" | "roastery" | "library";
}

export type SpaceKey = AmbianceFeature["key"];

export const ambianceFeatures: SpaceKey[] = [
  "interior",
  "courtyard",
  "roastery",
  "library",
];

export interface SpacePhoto {
  /** images.unsplash.com photo ID — Unsplash License, free for commercial use. */
  unsplashId?: string;
  /** Path under /public for a user-supplied photo. */
  localPhoto?: string;
}

/**
 * Photos for each physical space, shown on its detail page. Currently one
 * per space (reused from the homepage gallery); designed to hold several
 * once more angles are supplied.
 */
export const spacePhotos: Record<SpaceKey, SpacePhoto[]> = {
  interior: [1, 2, 3, 4, 5, 6, 7].map((n) => ({ localPhoto: `/space-photos/interior-${n}.webp` })),
  courtyard: [1, 2, 3, 4, 5, 6].map((n) => ({ localPhoto: `/space-photos/courtyard-${n}.webp` })),
  roastery: [1, 2, 3, 4].map((n) => ({ localPhoto: `/space-photos/roastery-${n}.webp` })),
  library: [1, 2, 3, 4].map((n) => ({ localPhoto: `/space-photos/library-${n}.webp` })),
};

export interface GalleryPhoto {
  id: string;
  captionKey: string;
  /** images.unsplash.com photo ID — Unsplash License, free for commercial use. */
  unsplashId?: string;
  /** Path under /public for a user-supplied photo. */
  localPhoto?: string;
}

export const galleryPhotos: GalleryPhoto[] = [
  { id: "g1", captionKey: "ambiance.features.interior.title", localPhoto: "/gallery-photos/interior.webp" },
  { id: "g2", captionKey: "ambiance.features.courtyard.title", localPhoto: "/gallery-photos/courtyard.webp" },
  { id: "g3", captionKey: "ambiance.features.roastery.title", localPhoto: "/gallery-photos/roastery.webp" },
  { id: "g4", captionKey: "ambiance.features.library.title", localPhoto: "/gallery-photos/library.webp" },
  { id: "g5", captionKey: "categories.items.coffee.name", unsplashId: "1426174840074-541ae41efdb9" },
  { id: "g6", captionKey: "categories.items.pastry.name", localPhoto: "/gallery-photos/pastry.webp" },
];

export const stats = [
  { key: "cups", value: 120000, suffix: "+", decimals: 0 },
  { key: "beans", value: 3, suffix: "", decimals: 0 },
  { key: "rating", value: 4.9, suffix: "", decimals: 1 },
  { key: "years", value: 4, suffix: "+", decimals: 0 },
] as const;
